exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("cities")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("cities").insert([
        { name: "Taipei" },
        { name: "Hong Kong" },
        { name: "Macau" },
        { name: "Bangkok" },
        { name: "Phuket" },
        { name: "Singapore" },
        { name: "Helsinki" },
        { name: "Järpen" },
        { name: "Trondheim" },
        { name: "Stockholm" },
        { name: "San Francisco" },
        { name: "Oslo" },
        { name: "Växjö" },
        { name: "Göteborg" },
        { name: "Warszawa" },
        { name: "SkåneTranås" },
        { name: "Pedersker" },
        { name: "Stavanger" },
        { name: "Malmö" },
        { name: "København" },
        { name: "Hørve" },
        { name: "Leynar" },
        { name: "Aarhus" },
        { name: "Præstø" },
        { name: "Vejle" },
        { name: "Fredericia" },
        { name: "Henne" },
        { name: "Budapest" },
        { name: "Praha" },
        { name: "Wien" },
        { name: "Waternish  IV GA" },
        { name: "Anstruther  KY AA" },
        { name: "Peat Inn  KY LH" },
        { name: "Auchterarder  PH NF" },
        { name: "Leith  EH LX" },
        { name: "Leith  EH RA" },
        { name: "Edinburgh  EH AB" },
        { name: "Edinburgh  EH EQ" },
        { name: "Newcastle upon Tyne  NE RF" },
        { name: "Dalry  KA LN" },
        { name: "Summerhouse  DL UD" },
        { name: "Hallwang" },
        { name: "Salzburg" },
        { name: "Harome  YO JE" },
        { name: "Oldstead  YO BL" },
        { name: "Zagreb" },
        { name: "South Dalton  HU PN" },
        { name: "Pateley Bridge  HG RL" },
        { name: "Winteringham  DN ND" },
        { name: "Grasmere  LA RN" },
        { name: "Morston  NR AA" },
        { name: "BownessonWindermere  LA NE" },
        { name: "Leeds  LS JH" },
        { name: "Cartmel  LA PZ" },
        { name: "Cartmel  LA QD" },
        { name: "Hunstanton  PE HZ" },
        { name: "Fence  BB QA" },
        { name: "Langho  BB BE" },
        { name: "Baslow  DE RR" },
        { name: "Belfast  BT LA" },
        { name: "Belfast  BT PF" },
        { name: "Aughton  L RT" },
        { name: "Nottingham  NG SA" },
        { name: "Upper Hambleton  LE TH" },
        { name: "Lovran" },
        { name: "Mountsorrel  LE AR" },
        { name: "Birkenhead  CH SG" },
        { name: "Dubrovnik" },
        { name: "Cambridge  CB HA" },
        { name: "Chester  CH LT" },
        { name: "Athína" },
        { name: "Kleinwalsertal" },
        { name: "Little Dunmow  CM HT" },
        { name: "Šibenik" },
        { name: "Rovinj" },
        { name: "Hampton in Arden  B ODQ" },
        { name: "Birmingham  B DH" },
        { name: "Birmingham  B UG" },
        { name: "Kenilworth  CV EZ" },
        { name: "Birmingham  B DU" },
        { name: "Birmingham  B EZ" },
        { name: "Menai Bridge/Porthaethwy  LL EE" },
        { name: "Fordwich  CT DB" },
        { name: "Seasalter  CT BP" },
        { name: "Llandrillo  LL OST" },
        { name: "StratforduponAvon  CV HB" },
        { name: "Spitalfields  E DY" },
        { name: "Finsbury  ECM AF" },
        { name: "Clerkenwell  ECM AY" },
        { name: "London" },
        { name: "Bermondsey  SE JX" },
        { name: "Regent's Park  WW QQ" },
        { name: "Marylebone  WU DB" },
        { name: "Marylebone  WU DG" },
        { name: "Mayfair  WS NQ" },
        { name: "Mayfair  WS XG" },
        { name: "Saint James's  SWY AH" },
        { name: "Mayfair  WS BF" },
        { name: "Mayfair  WB BR" },
        { name: "Saint James's  SWY QQ" },
        { name: "Mayfair  WB RS" },
        { name: "Mayfair  WS YF" },
        { name: "Mayfair  WJ LX" },
        { name: "Mayfair  WJ PU" },
        { name: "Marylebone  WH JZ" },
        { name: "Mayfair  WJ QB" },
        { name: "Marylebone  WH BY" },
        { name: "Mayfair  WS JH" },
        { name: "Mayfair  WJ BS" },
        { name: "Westminster  WJ BR" },
        { name: "Mayfair  WK AL" },
        { name: "Saint James's  SWA LS" },
        { name: "Mayfair  WK QR" },
        { name: "Mayfair  WJ NB" },
        { name: "Mayfair  WJ PP" },
        { name: "Mayfair  WK QU" },
        { name: "Mayfair  WJ NY" },
        { name: "Mayfair  WK QA" },
        { name: "Mayfair  WK BE" },
        { name: "Victoria  SWE AF" },
        { name: "Belgravia  SWX TA" },
        { name: "Belgravia  SWX RL" },
        { name: "Victoria  SWW JW" },
        { name: "Hyde Park  SWX LA" },
        { name: "North Kensington  W AQ" },
        { name: "Belgravia  SWX EA" },
        { name: "Victoria  SWV DE" },
        { name: "Belgravia  SWX JT" },
        { name: "North Kensington  W PN" },
        { name: "Chelsea  SW SP" },
        { name: "Chelsea  SW RD" },
        { name: "Chelsea  SW NT" },
        { name: "Kensington  W AH" },
        { name: "Chelsea  SW HP" },
        { name: "Montgomery/Trefaldwyn  SY PN" },
        { name: "Clapham Common  SW JG" },
        { name: "Fulham  SW QP" },
        { name: "Murcott  OX RE" },
        { name: "Hammersmith  W HA" },
        { name: "Chiswick  W EU" },
        { name: "Wandsworth  SW EG" },
        { name: "Kew  TW PZ" },
        { name: "Biddenden  TN AH" },
        { name: "Great Milton  OX PD" },
        { name: "Oxford  OX HQ" },
        { name: "Marlow  SL LS" },
        { name: "Marlow  SL BP" },
        { name: "Bray  SL AB" },
        { name: "Bray  SL AQ" },
        { name: "Bray  SL AT" },
        { name: "Burchett's Green  SL QZ" },
        { name: "Egham  TW UR" },
        { name: "City Centre  D" },
        { name: "Ascot  SL SE" },
        { name: "Blackrock" },
        { name: "Machynlleth  SY TA" },
        { name: "Cheltenham  GL AQ" },
        { name: "Ripley  GU AQ" },
        { name: "Dorking  RH JU" },
        { name: "Bagshot  GU EU" },
        { name: "Gravetye  RH LJ" },
        { name: "Shinfield  RG BY" },
        { name: "Horsham  RH HU" },
        { name: "Newbury  RG AQ" },
        { name: "Newbury  RG BN" },
        { name: "Malmesbury  SN RB" },
        { name: "Whitebrook  NP TX" },
        { name: "Llanddewi Skirrid  NP AW" },
        { name: "Castle Combe  SN HR" },
        { name: "Colerne  SN AZ" },
        { name: "East Chisenbury  SN AQ" },
        { name: "Winchester  SO HX" },
        { name: "Bath" },
        { name: "Bristol" },
        { name: "Chew Magna  BS TQ" },
        { name: "Penarth  CF AU" },
        { name: "Galway" },
        { name: "Cill Chainnigh/Kilkenny" },
        { name: "Baile Mhic Andáin/Thomastown" },
        { name: "Lios Dúin Bhearna/Lisdoonvarna" },
        { name: "Ilfracombe  EX DJ" },
        { name: "Knowstone  EX RY" },
        { name: "Lympstone  EX NZ" },
        { name: "Aird Mhór/Ardmore" },
        { name: "Chagford  TQ HH" },
        { name: "Torquay  TQ BH" },
        { name: "Corcaigh/Cork" },
        { name: "Port Isaac" },
        { name: "Padstow  PL AP" },
        { name: "Saint Helier/SaintHélier  JE TQ" },
        { name: "Saint Helier/SaintHélier  JE UH" },
        { name: "Portscatho  TR EW" },
        { name: "Ballydehob" },
        { name: "Baltimore" },
        { name: "Chicago" },
        { name: "New York" },
        { name: "Washington, D.C." }
        // { name: "Taipei" },
        // { name: "Hong Kong" },
        // { name: "Macau" },
        // { name: "Bangkok" },
        // { name: "Phuket" },
        // { name: "Singapore" },
        // { name: "Helsinki" },
        // { name: "Trondheim" },
        // { name: "Stockholm" },
        // { name: "San Francisco" },
        // { name: "Oslo" },
        // { name: "Växjö" },
        // { name: "Göteborg" },
        // { name: "Warszawa" },
        // { name: "Pedersker" },
        // { name: "Stavanger" },
        // { name: "Malmö" },
        // { name: "København" },
        // { name: "Hørve" },
        // { name: "Aarhus" },
        // { name: "Præstø" },
        // { name: "Vejle" },
        // { name: "Fredericia" },
        // { name: "Budapest" },
        // { name: "Praha" },
        // { name: "Wien" },
        // { name: "Waternish" },
        // { name: "Järpen" },
        // { name: "SkåneTranås" },
        // { name: "Leynar" },
        // { name: "Henne" },
        // { name: "Auchterarder" },
        // { name: "Mayfair" }
        // { name: "Kruishoutem", country_name: "Belgium" },
        // { name: "Shanghai", country_name: "China" },
        // { name: "Copenhagen", country_name: "Denmark" },
        // { name: "Chagny", country_name: "France" },
        // { name: "Collonges-au-Mont-d'Or", country_name: "France" },
        // { name: "Courchevel", country_name: "France" },
        // { name: "Eugénie-les-Bains", country_name: "France" },
        // { name: "Fontjoncouse", country_name: "France" },
        // { name: "Illhaeusern", country_name: "France" },
        // { name: "Le Castellet", country_name: "France" },
        // { name: "Les Belleville", country_name: "France" },
        // { name: "Manigod", country_name: "France" },
        // { name: "Marseille", country_name: "France" },
        // { name: "Megève", country_name: "France" },
        // { name: "Monte Carlo", country_name: "Monaco" },
        // { name: "Ouches", country_name: "France" },
        // { name: "Paris", country_name: "France" },
        // { name: "Saint-Bonnet-le-Froid", country_name: "France" },
        // { name: "Saint-Tropez", country_name: "France" },
        // { name: "Tinqueux", country_name: "France" },
        // { name: "Valence", country_name: "France" },
        // { name: "Vonnas", country_name: "France" },
        // { name: "Baiersbronn", country_name: "Germany" },
        // { name: "Bergisch Gladbach", country_name: "Germany" },
        // { name: "Dreis", country_name: "Germany" },
        // { name: "Hamburg", country_name: "Germany" },
        // { name: "Munich", country_name: "Germany" },
        // { name: "Perl", country_name: "Germany" },
        // { name: "Rottach-Egern", country_name: "Germany" },
        // { name: "Saarbrücken", country_name: "Germany" },
        // { name: "Wolfsburg", country_name: "Germany" },
        // { name: "Hong Kong", country_name: "Hong Kong" },
        // { name: "Macao", country_name: "Macao" },
        // { name: "Alba", country_name: "Italy" },
        // { name: "Brusaporto", country_name: "Italy" },
        // { name: "Canneto sull'Oglio", country_name: "Italy" },
        // { name: "Castel di Sangro", country_name: "Italy" },
        // { name: "FLorence", country_name: "Italy" },
        // { name: "Modena", country_name: "Italy" },
        // { name: "Rome", country_name: "Italy" },
        // { name: "Rubano", country_name: "Italy" },
        // { name: "San Cassiano", country_name: "Italy" },
        // { name: "Senigallia", country_name: "Italy" },
        // { name: "Fukuoka", country_name: "Japan" },
        // { name: "Hiroshima", country_name: "Japan" },
        // { name: "Hokkaido", country_name: "Japan" },
        // { name: "Kobe", country_name: "Japan" },
        // { name: "Kyoto", country_name: "Japan" },
        // { name: "Nara", country_name: "Japan" },
        // { name: "Osaka", country_name: "Japan" },
        // { name: "Shōnan", country_name: "Japan" },
        // { name: "Tokyo", country_name: "Japan" },
        // { name: "Toyama", country_name: "Japan" },
        // { name: "Vaassen", country_name: "Netherlands" },
        // { name: "Zwolle", country_name: "Netherlands" },
        // { name: "Oslo", country_name: "Norway" },
        // { name: "Seoul", country_name: "South Korea" },
        // { name: "Barcelona", country_name: "Spain" },
        // { name: "El Puerto de Santa María", country_name: "Spain" },
        // { name: "Girnoa", country_name: "Spain" },
        // { name: "Lasarte-Oria", country_name: "Spain" },
        // { name: "Larrabetzu", country_name: "Spain" },
        // { name: "Madrid", country_name: "Spain" },
        // { name: "Marbella", country_name: "Spain" },
        // { name: "San Sebastián", country_name: "Spain" },
        // { name: "Dénia", country_name: "Spain" },
        // { name: "Stockholm", country_name: "Sweden" },
        // { name: "Basel", country_name: "Switzerland" },
        // { name: "Crissier", country_name: "Switzerland" },
        // { name: "Fürstenau", country_name: "Switzerland" },
        // { name: "Taipei", country_name: "Taiwan" },
        // { name: "Bray", country_name: "United Kingdom" },
        // { name: "London", country_name: "United Kingdom" },
        // { name: "Chicago", country_name: "United States" },
        // { name: "Healdsburg", country_name: "United States" },
        // { name: "Los Gatos", country_name: "United States" },
        // { name: "New York City", country_name: "United States" },
        // { name: "San Francisco", country_name: "United States" },
        // { name: "St. Helena", country_name: "United States" },
        // { name: "Washington", country_name: "United States" },
        // { name: "Yountville", country_name: "United States" }
      ]);
    });
};
