exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("cuisines")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("cuisines").insert([
        { name: "Taiwanese" },
        { name: "Steakhouse" },
        { name: "French contemporary" },
        { name: "Sushi" },
        { name: "Barbecue" },
        { name: "Hang Zhou" },
        { name: "Asian contemporary" },
        { name: "Cantonese" },
        { name: "Japanese" },
        { name: "European contemporary" },
        { name: "Innovative" },
        { name: "Seafood" },
        { name: "Dim Sum" },
        { name: "Teppanyaki" },
        { name: "Noodles and congee" },
        { name: "French" },
        { name: "Shanghainese" },
        { name: "Italian" },
        { name: "Cantonese Roast Meats" },
        { name: "Taizhou" },
        { name: "Sichuan" },
        { name: "Indian" },
        { name: "Thai" },
        { name: "Southern Thai" },
        { name: "Thai Contemporary" },
        { name: "Street Food" },
        { name: "Fujian" },
        { name: "Australian" },
        { name: "Chinese" },
        { name: "Italian contemporary" },
        { name: "Peranakan" },
        { name: "Modern cuisine" },
        { name: "Finnish" },
        { name: "Creative" },
        { name: "Meats and grills" },
        { name: "Classic cuisine" },
        { name: "Contemporary" },
        { name: "Californian" },
        { name: "American" },
        { name: "Fusion" },
        { name: "International" },
        { name: "Moroccan" },
        { name: "Korean" },
        { name: "Scandinavian" },
        { name: "Danish" },
        { name: "Classic French" },
        { name: "Vegetarian" },
        { name: "Japanese contemporary" },
        { name: "Sichuan-Huai Yang" },
        { name: "Hunanese and Sichuan" },
        { name: "Mexican" },
        { name: "Creative French" },
        { name: "Asian" }
      ]);
    });
};
