exports.seed = function(knex) {
    return knex("restaurants").del().then(function() {
        return knex("restaurants").insert([
            { name: 'Golden Formosa',
                stars: 1,
                price: '$$',
                cuisine_name: 'Taiwanese',
                city_name: 'Taipei' },
            { name: 'Danny\'s Steakhouse',
                stars: 1,
                price: '$$',
                cuisine_name: 'Steakhouse',
                city_name: 'Taipei' },
            { name: 'L\'Atelier de Joël Robuchon',
                stars: 1,
                price: '$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Taipei' },
            { name: 'Kitcho',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Taipei' },
            { name: 'Da-Wan',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Barbecue',
                city_name: 'Taipei' },
            { name: 'Sushi Nomura',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Sushi',
                city_name: 'Taipei' },
            { name: 'Tien Hsiang Lo',
                stars: 1,
                price: '$$',
                cuisine_name: 'Hang Zhou',
                city_name: 'Taipei' },
            { name: 'logy',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Asian contemporary',
                city_name: 'Taipei' },
            { name: 'Ya Ge',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Taipei' },
            { name: 'Ken An Ho',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'Taipei' },
            { name: 'MUME',
                stars: 1,
                price: '$$$',
                cuisine_name: 'European contemporary',
                city_name: 'Taipei' },
            { name: 'Ming Fu',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Taiwanese',
                city_name: 'Taipei' },
            { name: 'Sushi Ryu',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Taipei' },
            { name: 'Impromptu by Paul Lee',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Innovative',
                city_name: 'Taipei' },
            { name: 'Longtail',
                stars: 1,
                price: '$$',
                cuisine_name: 'Innovative',
                city_name: 'Taipei' },
            { name: 'Mountain and Sea House',
                stars: 1,
                price: '$$',
                cuisine_name: 'Taiwanese',
                city_name: 'Taipei' },
            { name: 'Da San Yuan',
                stars: 1,
                price: '$',
                cuisine_name: 'Cantonese',
                city_name: 'Taipei' },
            { name: 'Tainan Tan Tsu Mien Seafood',
                stars: 1,
                price: '$$',
                cuisine_name: 'Seafood',
                city_name: 'Taipei' },
            { name: 'Loaf On',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Lei Garden (Kwun Tong)',
                stars: 1,
                price: '$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Tim Ho Wan (Sham Shui Po)',
                stars: 1,
                price: '$',
                cuisine_name: 'Dim Sum',
                city_name: 'Hong Kong' },
            { name: 'Lei Garden (Mong Kok)',
                stars: 1,
                price: '$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Ming Court',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Yat Tung Heen (Jordan)',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'IM Teppanyaki & Wine',
                stars: 1,
                price: '$$',
                cuisine_name: 'Teppanyaki',
                city_name: 'Hong Kong' },
            { name: 'Shang Palace',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Fu Ho (Tsim Sha Tsui)',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Yee Tung Heen',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Ah Yat Harbour View (Tsim Sha Tsui)',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Rech',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Seafood',
                city_name: 'Hong Kong' },
            { name: 'Spring Moon',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Ho Hung Kee',
                stars: 1,
                price: '$',
                cuisine_name: 'Noodles and congee',
                city_name: 'Hong Kong' },
            { name: 'Imperial Treasure Fine Chinese Cuisine',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Sushi Tokami',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Hong Kong' },
            { name: 'Épure',
                stars: 1,
                price: '$$$',
                cuisine_name: 'French',
                city_name: 'Hong Kong' },
            { name: 'Yè Shanghai (Tsim Sha Tsui)',
                stars: 1,
                price: '$',
                cuisine_name: 'Shanghainese',
                city_name: 'Hong Kong' },
            { name: 'Tosca',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Italian',
                city_name: 'Hong Kong' },
            { name: 'Jardin de Jade (Wan Chai)',
                stars: 1,
                price: '$$',
                cuisine_name: 'Shanghainese',
                city_name: 'Hong Kong' },
            { name: 'Zhejiang Heen',
                stars: 1,
                price: '$$',
                cuisine_name: 'Shanghainese',
                city_name: 'Hong Kong' },
            { name: 'Pang\'s Kitchen',
                stars: 1,
                price: '$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Takumi by Daisuke Mori',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Hong Kong' },
            { name: 'Kam\'s Roast Goose',
                stars: 1,
                price: '$',
                cuisine_name: 'Cantonese Roast Meats',
                city_name: 'Hong Kong' },
            { name: 'Xin Rong Ji',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Taizhou',
                city_name: 'Hong Kong' },
            { name: 'Qi (Wan Chai)',
                stars: 1,
                price: '$',
                cuisine_name: 'Sichuan',
                city_name: 'Hong Kong' },
            { name: 'The Ocean',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'French',
                city_name: 'Hong Kong' },
            { name: 'Summer Palace',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Man Wah',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Octavium',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Italian',
                city_name: 'Hong Kong' },
            { name: 'Guo Fu Lou',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Mandarin Grill + Bar',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'European contemporary',
                city_name: 'Hong Kong' },
            { name: 'Arbor',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Innovative',
                city_name: '' },
            { name: 'Yat Lok',
                stars: 1,
                price: '$',
                cuisine_name: 'Cantonese Roast Meats',
                city_name: 'Hong Kong' },
            { name: 'Duddell\'s',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Beefbar',
                stars: 1,
                price: '$$',
                cuisine_name: 'Steakhouse',
                city_name: 'Hong Kong' },
            { name: 'Arcane',
                stars: 1,
                price: '$$$',
                cuisine_name: 'European contemporary',
                city_name: 'Hong Kong' },
            { name: 'Sushi Wadatsumi',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Sushi',
                city_name: 'Hong Kong' },
            { name: 'VEA',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Hong Kong' },
            { name: 'Celebrity Cuisine',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'New Punjab Club',
                stars: 1,
                price: '$$',
                cuisine_name: 'Indian',
                city_name: 'Hong Kong' },
            { name: 'Belon',
                stars: 1,
                price: '$$$',
                cuisine_name: 'French',
                city_name: 'Hong Kong' },
            { name: 'Tate',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Hong Kong' },
            { name: 'Kaiseki Den by Saotome',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Japanese',
                city_name: 'Hong Kong' },
            { name: 'Wing Lei',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Macau' },
            { name: 'The Kitchen',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Steakhouse',
                city_name: 'Macau' },
            { name: 'Tim\'s Kitchen',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Macau' },
            { name: 'King',
                stars: 1,
                price: '$',
                cuisine_name: 'Cantonese',
                city_name: 'Macau' },
            { name: 'Ying',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Macau' },
            { name: 'Shinji by Kanesaka',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Macau' },
            { name: 'The Golden Peacock',
                stars: 1,
                price: '$',
                cuisine_name: 'Indian',
                city_name: 'Macau' },
            { name: 'Zi Yat Heen',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Macau' },
            { name: 'Pearl Dragon',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Macau' },
            { name: '8 1/2 Otto e Mezzo - Bombana',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Italian',
                city_name: 'Macau' },
            { name: 'Lai Heen',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Macau' },
            { name: 'Suan Thip',
                stars: 1,
                price: '$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'Upstairs at Mikkeller',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Bangkok' },
            { name: 'R-Haan',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'Canvas',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Bangkok' },
            { name: 'Chim by Siam Wisdom',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'Bo.lan',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'Sorn',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Southern Thai',
                city_name: 'Bangkok' },
            { name: 'Elements',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Bangkok' },
            { name: 'Sra Bua by Kiin Kiin',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Thai Contemporary',
                city_name: 'Bangkok' },
            { name: 'Savelberg',
                stars: 1,
                price: '$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Bangkok' },
            { name: 'Paste',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'Ginza Sushi ichi',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Bangkok' },
            { name: 'Saneh Jaan',
                stars: 1,
                price: '$$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'Gaa',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Bangkok' },
            { name: 'J\'AIME by Jean-Michel Lorain',
                stars: 1,
                price: '$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Bangkok' },
            { name: 'Nahm',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'Saawaan',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Thai Contemporary',
                city_name: 'Bangkok' },
            { name: 'Le Du',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'Methavalai Sorndaeng',
                stars: 1,
                price: '$$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'Jay Fai',
                stars: 1,
                price: '$$',
                cuisine_name: 'Street Food',
                city_name: 'Bangkok' },
            { name: 'Ruean Panya',
                stars: 1,
                price: '$$',
                cuisine_name: 'Thai',
                city_name: 'Bangkok' },
            { name: 'PRU',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Phuket' },
            { name: 'Putien (Kitchener Road)',
                stars: 1,
                price: '$',
                cuisine_name: 'Fujian',
                city_name: 'Singapore' },
            { name: 'Hill Street Tai Hwa Pork Noodle',
                stars: 1,
                price: '$',
                cuisine_name: 'Street Food',
                city_name: 'Singapore' },
            { name: 'Chef Kang\'s',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Singapore' },
            { name: 'Garibaldi',
                stars: 1,
                price: '$',
                cuisine_name: 'Italian',
                city_name: 'Singapore' },
            { name: 'Summer Pavilion',
                stars: 1,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Singapore' },
            { name: 'Shinji (Bras Basah Road)',
                stars: 1,
                price: '$$',
                cuisine_name: 'Sushi',
                city_name: 'Singapore' },
            { name: 'The Song of India',
                stars: 1,
                price: '$',
                cuisine_name: 'Indian',
                city_name: 'Singapore' },
            { name: 'Lei Garden',
                stars: 1,
                price: '$',
                cuisine_name: 'Cantonese',
                city_name: 'Singapore' },
            { name: 'Whitegrass',
                stars: 1,
                price: '$$',
                cuisine_name: 'Australian',
                city_name: 'Singapore' },
            { name: 'Alma',
                stars: 1,
                price: '$',
                cuisine_name: 'European contemporary',
                city_name: 'Singapore' },
            { name: 'Jaan',
                stars: 1,
                price: '$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Singapore' },
            { name: 'Labyrinth',
                stars: 1,
                price: '$$',
                cuisine_name: 'Innovative',
                city_name: 'Singapore' },
            { name: 'Cut',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Steakhouse',
                city_name: 'Singapore' },
            { name: 'Béni',
                stars: 1,
                price: '$$',
                cuisine_name: 'French contemporary',
                city_name: 'Singapore' },
            { name: 'Crystal Jade Golden Palace',
                stars: 1,
                price: '$',
                cuisine_name: 'Chinese',
                city_name: 'Singapore' },
            { name: 'Imperial Treasure Fine Teochew Cuisine (Orchard)',
                stars: 1,
                price: '$',
                cuisine_name: 'Chinese',
                city_name: 'Singapore' },
            { name: 'Sushi Ichi',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Sushi',
                city_name: 'Singapore' },
            { name: 'Sushi Kimura',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Singapore' },
            { name: 'Saint Pierre',
                stars: 1,
                price: '$$',
                cuisine_name: 'French contemporary',
                city_name: 'Singapore' },
            { name: 'Iggy\'s',
                stars: 1,
                price: '$$$',
                cuisine_name: 'European contemporary',
                city_name: 'Singapore' },
            { name: 'Jiang-Nan Chun',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Singapore' },
            { name: 'Braci',
                stars: 1,
                price: '$$',
                cuisine_name: 'Italian contemporary',
                city_name: 'Singapore' },
            { name: 'Corner House',
                stars: 1,
                price: '$$',
                cuisine_name: 'Innovative',
                city_name: 'Singapore' },
            { name: 'Shinji (Tanglin Road)',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Singapore' },
            { name: 'Bacchanalia',
                stars: 1,
                price: '$$',
                cuisine_name: 'Innovative',
                city_name: 'Singapore' },
            { name: 'Summer Palace',
                stars: 1,
                price: '$',
                cuisine_name: 'Cantonese',
                city_name: 'Singapore' },
            { name: 'Cheek by Jowl',
                stars: 1,
                price: '$',
                cuisine_name: 'Australian',
                city_name: 'Singapore' },
            { name: 'Nouri',
                stars: 1,
                price: '$',
                cuisine_name: 'Innovative',
                city_name: 'Singapore' },
            { name: 'Liao Fan Hong Kong Soya Sauce Chicken Rice & Noodle',
                stars: 1,
                price: '$',
                cuisine_name: 'Street Food',
                city_name: 'Singapore' },
            { name: 'Burnt Ends',
                stars: 1,
                price: '$$',
                cuisine_name: 'Barbecue',
                city_name: 'Singapore' },
            { name: 'Rhubarb',
                stars: 1,
                price: '$',
                cuisine_name: 'French contemporary',
                city_name: 'Singapore' },
            { name: 'Meta',
                stars: 1,
                price: '$$',
                cuisine_name: 'Innovative',
                city_name: 'Singapore' },
            { name: 'Candlenut',
                stars: 1,
                price: '$',
                cuisine_name: 'Peranakan',
                city_name: 'Singapore' },
            { name: 'Ma Cuisine',
                stars: 1,
                price: '$',
                cuisine_name: 'French',
                city_name: 'Singapore' },
            { name: 'Ask',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Helsingfors / Helsinki' },
            { name: 'Palace',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Helsingfors / Helsinki' },
            { name: 'Olo',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Helsingfors / Helsinki' },
            { name: 'Demo',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Helsingfors / Helsinki' },
            { name: 'Grön',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Finnish',
                city_name: 'Helsingfors / Helsinki' },
            { name: 'Ora',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Helsingfors / Helsinki' },
            { name: 'Credo',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Trondheim' },
            { name: 'FAGN',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Trondheim' },
            { name: 'Volt',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Creative',
                city_name: 'Stockholm' },
            { name: 'Agrikultur',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Stockholm' },
            { name: 'Ekstedt',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Meats and grills',
                city_name: 'Stockholm' },
            { name: 'Mathias Dahlgren-Matbaren',
                stars: 1,
                price: '$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Stockholm' },
            { name: 'Operakällaren',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Classic cuisine',
                city_name: 'Stockholm' },
            { name: 'Sushi Sho',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Japanese',
                city_name: 'Stockholm' },
            { name: 'Aloë',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Stockholm' },
            { name: 'Madrona Manor',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Farmhouse Inn & Restaurant',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Californian',
                city_name: 'San Francisco' },
            { name: 'Auberge du Soleil',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Californian',
                city_name: 'San Francisco' },
            { name: 'Bouchon',
                stars: 1,
                price: '$$$',
                cuisine_name: 'French',
                city_name: 'San Francisco' },
            { name: 'Madcap',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Kenzo',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'San Francisco' },
            { name: 'La Toque',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Wako',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'San Francisco' },
            { name: 'Spruce',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Californian',
                city_name: 'San Francisco' },
            { name: 'Sorrel',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Californian',
                city_name: 'San Francisco' },
            { name: 'Bar Crenn',
                stars: 1,
                price: '$$$',
                cuisine_name: 'French',
                city_name: 'San Francisco' },
            { name: 'Gary Danko',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'SPQR',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Italian',
                city_name: 'San Francisco' },
            { name: 'Kinjo',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'San Francisco' },
            { name: 'jū-ni',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'San Francisco' },
            { name: 'State Bird Provisions',
                stars: 1,
                price: '$$',
                cuisine_name: 'American',
                city_name: 'San Francisco' },
            { name: 'The Progress',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Californian',
                city_name: 'San Francisco' },
            { name: 'Lord Stanley',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Californian',
                city_name: 'San Francisco' },
            { name: 'Octavia',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Californian',
                city_name: 'San Francisco' },
            { name: 'Keiko à Nob Hill',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Fusion',
                city_name: 'San Francisco' },
            { name: 'Rich Table',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Mister Jiu\'s',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Chinese',
                city_name: 'San Francisco' },
            { name: 'Sons & Daughters',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Nico',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Kin Khao',
                stars: 1,
                price: '$$',
                cuisine_name: 'Thai',
                city_name: 'San Francisco' },
            { name: 'Michael Mina',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Hashiri',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'San Francisco' },
            { name: 'Birdsong',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'American',
                city_name: 'San Francisco' },
            { name: 'Luce',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'In Situ',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'International',
                city_name: 'San Francisco' },
            { name: 'Mourad',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Moroccan',
                city_name: 'San Francisco' },
            { name: 'Commonwealth',
                stars: 1,
                price: '$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Omakase',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'San Francisco' },
            { name: 'Al\'s Place',
                stars: 1,
                price: '$$',
                cuisine_name: 'Californian',
                city_name: 'San Francisco' },
            { name: 'Maum',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Korean',
                city_name: 'South San Francisco' },
            { name: 'Rasa',
                stars: 1,
                price: '$$',
                cuisine_name: 'Indian',
                city_name: 'San Francisco' },
            { name: 'Sushi Yoshizumi',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'San Francisco' },
            { name: 'Wakuriya',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'San Francisco' },
            { name: 'The Village Pub',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Madera',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Protégé',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Contemporary',
                city_name: 'South San Francisco' },
            { name: 'Chez TJ',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'South San Francisco' },
            { name: 'Plumed Horse',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'South San Francisco' },
            { name: 'Kontrast',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Scandinavian',
                city_name: 'Oslo' },
            { name: 'Statholdergaarden',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Classic cuisine',
                city_name: 'Oslo' },
            { name: 'Galt',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Oslo' },
            { name: 'PM & Vänner',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Creative',
                city_name: 'Växjö' },
            { name: 'Upper House',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Göteborg' },
            { name: 'SK Mat & Människor',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Göteborg' },
            { name: 'Bhoga',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Creative',
                city_name: 'Göteborg' },
            { name: '28+',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Göteborg' },
            { name: 'Thörnströms Kök',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Classic cuisine',
                city_name: 'Göteborg' },
            { name: 'Koka',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Göteborg' },
            { name: 'Senses',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Warszawa' },
            { name: 'atelier Amaro',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Warszawa' },
            { name: 'Kadeau Bornholm',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Pedersker' },
            { name: 'Sabi Omakase',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Stavanger' },
            { name: 'RE-NAA',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Stavanger' },
            { name: 'Bloom in the Park',
                stars: 1,
                price: '$$',
                cuisine_name: 'Creative',
                city_name: 'Malmö' },
            { name: 'Søllerød Kro',
                stars: 1,
                price: '$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København' },
            { name: 'SAV',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Creative',
                city_name: 'Malmö' },
            { name: 'Jordnær',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Danish',
                city_name: 'København' },
            { name: 'Kokkeriet',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København   K' },
            { name: '108',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København   K' },
            { name: 'Clou',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København   K' },
            { name: 'Stud!o at The Standard',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Creative',
                city_name: 'København   K' },
            { name: 'Marchal',
                stars: 1,
                price: '$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København   K' },
            { name: 'Kiin Kiin',
                stars: 1,
                price: '$$',
                cuisine_name: 'Thai',
                city_name: 'København   N' },
            { name: 'Kong Hans Kælder',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Classic French',
                city_name: 'København   K' },
            { name: 'Era Ora',
                stars: 1,
                price: '$$',
                cuisine_name: 'Italian',
                city_name: 'København   K' },
            { name: 'Relæ',
                stars: 1,
                price: '$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København   N' },
            { name: 'Alouette',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København   S' },
            { name: 'formel B',
                stars: 1,
                price: '$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København   C' },
            { name: 'Slotskøkkenet',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Hørve' },
            { name: 'Domestic',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Aarhus' },
            { name: 'Gastromé',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Aarhus' },
            { name: 'Substans',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Aarhus' },
            { name: 'Frederikshøj',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Aarhus' },
            { name: 'Frederiksminde',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Creative',
                city_name: 'Præstø' },
            { name: 'Me‚Mu',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Vejle' },
            { name: 'Ti Trin Ned',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Fredericia' },
            { name: 'Stand',
                stars: 1,
                price: '$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Budapest' },
            { name: 'Borkonyha Winekitchen',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Budapest' },
            { name: 'Costes Downtown',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Budapest' },
            { name: 'Costes',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Budapest' },
            { name: 'Babel',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Budapest' },
            { name: 'La Degustation Bohême Bourgeoise',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Praha' },
            { name: 'Field',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Praha' },
            { name: 'Das Loft',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Wien' },
            { name: 'Edvard',
                stars: 1,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Wien' },
            { name: 'Walter Bauer',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Classic cuisine',
                city_name: 'Wien' },
            { name: 'Pramerl & the Wolf',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Creative',
                city_name: 'Wien' },
            { name: 'Tian',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Vegetarian',
                city_name: 'Wien' },
            { name: 'SHIKI',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Japanese',
                city_name: 'Wien' },
            { name: 'Le Ciel by Toni Mörwald',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Classic cuisine',
                city_name: 'Wien' },
            { name: 'aend',
                stars: 1,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Wien' },
            { name: 'RAW',
                stars: 2,
                price: '$$$',
                cuisine_name: 'Innovative',
                city_name: 'Taipei' },
            { name: 'Shoun RyuGin',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Japanese contemporary',
                city_name: 'Taipei' },
            { name: 'Taïrroir',
                stars: 2,
                price: '$$$',
                cuisine_name: 'Innovative',
                city_name: 'Taipei' },
            { name: 'Sushi Amamoto',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Taipei' },
            { name: 'The Guest House',
                stars: 2,
                price: '$$',
                cuisine_name: 'Sichuan-Huai Yang',
                city_name: 'Taipei' },
            { name: 'Sun Tung Lok',
                stars: 2,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Yan Toh Heen',
                stars: 2,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Forum',
                stars: 2,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Tin Lung Heen',
                stars: 2,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Tenku RyuGin',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Japanese',
                city_name: 'Hong Kong' },
            { name: 'Sushi Saito',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Hong Kong' },
            { name: 'Pierre',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Hong Kong' },
            { name: 'Ying Jee Club',
                stars: 2,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Amber',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Hong Kong' },
            { name: 'Écriture',
                stars: 2,
                price: '$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Hong Kong' },
            { name: 'Ta Vie',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Hong Kong' },
            { name: 'Kashiwaya',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Japanese',
                city_name: 'Hong Kong' },
            { name: 'Feng Wei Ju',
                stars: 2,
                price: '$',
                cuisine_name: 'Hunanese and Sichuan',
                city_name: 'Macau' },
            { name: 'Golden Flower',
                stars: 2,
                price: '$$',
                cuisine_name: 'Chinese',
                city_name: 'Macau' },
            { name: 'Mizumi (Macau)',
                stars: 2,
                price: '$$',
                cuisine_name: 'Japanese',
                city_name: 'Macau' },
            { name: 'The Tasting Room',
                stars: 2,
                price: '$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Macau' },
            { name: 'Alain Ducasse at Morpheus',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Macau' },
            { name: 'Gaggan',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Bangkok' },
            { name: 'Sühring',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'European contemporary',
                city_name: 'Bangkok' },
            { name: 'Mezzaluna',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Bangkok' },
            { name: 'Le Normandie',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Bangkok' },
            { name: 'Waku Ghin',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Japanese contemporary',
                city_name: 'Singapore' },
            { name: 'Les Amis',
                stars: 2,
                price: '$$$',
                cuisine_name: 'French',
                city_name: 'Singapore' },
            { name: 'Shisen Hanten',
                stars: 2,
                price: '$',
                cuisine_name: 'Chinese',
                city_name: 'Singapore' },
            { name: 'Odette',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Singapore' },
            { name: 'Shoukouwa',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Singapore' },
            { name: 'Fäviken Magasinet',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Järpen' },
            { name: 'Gastrologik',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Stockholm' },
            { name: 'Oaxen Krog',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Stockholm' },
            { name: 'Acquerello',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Italian',
                city_name: 'San Francisco' },
            { name: 'Coi',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Campton Place',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Indian',
                city_name: 'San Francisco' },
            { name: 'Lazy Bear',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Saison',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Californian',
                city_name: 'San Francisco' },
            { name: 'Californios',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Mexican',
                city_name: 'San Francisco' },
            { name: 'Commis',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Baumé',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'South San Francisco' },
            { name: 'Daniel Berlin',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'SkåneTranås' },
            { name: 'Vollmers',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Malmö' },
            { name: 'noma',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'København   K' },
            { name: 'a‚o‚c',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København   K' },
            { name: 'Kadeau Copenhagen',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'København   K' },
            { name: 'KOKS',
                stars: 2,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'Leynar' },
            { name: 'Henne Kirkeby Kro',
                stars: 2,
                price: '$$$',
                cuisine_name: 'Classic cuisine',
                city_name: 'Henne' },
            { name: 'Onyx',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Budapest' },
            { name: 'Mraz & Sohn',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Creative',
                city_name: 'Wien' },
            { name: 'Konstantin Filippou',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Wien' },
            { name: 'Silvio Nickol Gourmet Restaurant',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Wien' },
            { name: 'Steirereck im Stadtpark',
                stars: 2,
                price: '$$$$$',
                cuisine_name: 'Creative',
                city_name: 'Wien' },
            { name: 'Le Palais',
                stars: 3,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Taipei' },
            { name: 'T\'ang Court',
                stars: 3,
                price: '$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Bo Innovation',
                stars: 3,
                price: '$$$$$',
                cuisine_name: 'Innovative',
                city_name: 'Hong Kong' },
            { name: 'Lung King Heen',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Cantonese',
                city_name: 'Hong Kong' },
            { name: 'Caprice',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'French',
                city_name: 'Hong Kong' },
            { name: '8½ Otto e Mezzo - Bombana',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Italian',
                city_name: 'Hong Kong' },
            { name: 'L\'Atelier de Joël Robuchon',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Hong Kong' },
            { name: 'Sushi Shikon',
                stars: 3,
                price: '$$$$$',
                cuisine_name: 'Sushi',
                city_name: 'Hong Kong' },
            { name: 'Robuchon au Dôme',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'French contemporary',
                city_name: 'Macau' },
            { name: 'The Eight',
                stars: 3,
                price: '$$$',
                cuisine_name: 'Chinese',
                city_name: 'Macau' },
            { name: 'Jade Dragon',
                stars: 3,
                price: '$$',
                cuisine_name: 'Cantonese',
                city_name: 'Macau' },
            { name: 'Frantzén',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Stockholm' },
            { name: 'SingleThread',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'The Restaurant at Meadowood',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'The French Laundry',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Atelier Crenn',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Quince',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'San Francisco' },
            { name: 'Benu',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Asian',
                city_name: 'San Francisco' },
            { name: 'Manresa',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Contemporary',
                city_name: 'South San Francisco' },
            { name: 'Maaemo',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Modern cuisine',
                city_name: 'Oslo' },
            { name: 'Geranium',
                stars: 3,
                price: '$$$$',
                cuisine_name: 'Creative',
                city_name: 'København   Ø' },
            { name: 'Amador',
                stars: 3,
                price: '$$$$$',
                cuisine_name: 'Creative',
                city_name: 'Wien' } 
        ]);
    });
};