exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("cities")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("cities").insert([
        { name: "Taipei", country_name: "Taiwan" },
        { name: "Hong Kong", country_name: "Hong Kong" },
        { name: "Macau", country_name: "Macau" },
        { name: "Bangkok", country_name: "Thailand" },
        { name: "Phuket", country_name: "Thailand" },
        { name: "Singapore", country_name: "Singapore" },
        { name: "Helsinki", country_name: "Finland" },
        { name: "Järpen", country_name: "Sweden" },
        { name: "Trondheim", country_name: "Norway" },
        { name: "Stockholm", country_name: "Sweden" },
        { name: "San Francisco", country_name: "United States" },
        { name: "Oslo", country_name: "Norway" },
        { name: "Växjö", country_name: "Sweden" },
        { name: "Göteborg", country_name: "Sweden" },
        { name: "Warszawa", country_name: "Poland" },
        { name: "SkåneTranås", country_name: "Sweden" },
        { name: "Pedersker", country_name: "Denmark" },
        { name: "Stavanger", country_name: "Norway" },
        { name: "Malmö", country_name: "Sweden" },
        { name: "Copenhagen", country_name: "Denmark" },
        { name: "Hørve", country_name: "Denmark" },
        { name: "Leynar", country_name: "Denmark" },
        { name: "Aarhus", country_name: "Denmark" },
        { name: "Præstø", country_name: "Denmark" },
        { name: "Vejle", country_name: "Denmark" },
        { name: "Fredericia", country_name: "Denmark" },
        { name: "Henne", country_name: "Denmark" },
        { name: "Budapest", country_name: "Hungary" },
        { name: "Praha", country_name: "Czech Republic" },
        { name: "Vienna", country_name: "Austria" },
        { name: "Waternish", country_name: "United Kingdom" },
        { name: "Anstruther", country_name: "United Kingdom" },
        { name: "Peat Inn", country_name: "United Kingdom" },
        { name: "Auchterarder", country_name: "United Kingdom" },
        { name: "Leith", country_name: "United Kingdom" },
        { name: "Edinburgh", country_name: "United Kingdom" },
        { name: "Newcastle upon Tyne", country_name: "United Kingdom" },
        { name: "Dalry", country_name: "United Kingdom" },
        { name: "Summerhouse", country_name: "United Kingdom" },
        { name: "Salzburg", country_name: "Austria" },
        { name: "Harome", country_name: "United Kingdom" },
        { name: "Oldstead", country_name: "United Kingdom" },
        { name: "Zagreb", country_name: "Croatia" },
        { name: "South Dalton", country_name: "United Kingdom" },
        { name: "Pateley Bridge", country_name: "United Kingdom" },
        { name: "Winteringham", country_name: "United Kingdom" },
        { name: "Grasmere", country_name: "United Kingdom" },
        { name: "Morston", country_name: "United Kingdom" },
        { name: "Bownesson-on-Windermere", country_name: "United Kingdom" },
        { name: "Leeds", country_name: "United Kingdom" },
        { name: "Cartmel", country_name: "United Kingdom" },
        { name: "Hunstanton", country_name: "United Kingdom" },
        { name: "Fence", country_name: "United Kingdom" },
        { name: "Langho", country_name: "United Kingdom" },
        { name: "Baslow", country_name: "United Kingdom" },
        { name: "Belfast", country_name: "Republic of Ireland" },
        { name: "Aughton", country_name: "United Kingdom" },
        { name: "Nottingham", country_name: "United Kingdom" },
        { name: "Upper Hambleton", country_name: "United Kingdom" },
        { name: "Lovran", country_name: "Croatia" },
        { name: "Mountsorrel", country_name: "United Kingdom" },
        { name: "Birkenhead", country_name: "United Kingdom" },
        { name: "Dubrovnik", country_name: "Croatia" },
        { name: "Cambridge", country_name: "United Kingdom" },
        { name: "Chester", country_name: "United Kingdom" },
        { name: "Athína", country_name: "Greece" },
        { name: "Kleinwalsertal", country_name: "Austria" },
        { name: "Little Dunmow", country_name: "United Kingdom" },
        { name: "Šibenik", country_name: "Croatia" },
        { name: "Rovinj", country_name: "Croatia" },
        { name: "Hampton in Arden", country_name: "United Kingdom" },
        { name: "Birmingham", country_name: "United Kingdom" },
        { name: "Kenilworth", country_name: "United Kingdom" },
        { name: "Menai Bridge", country_name: "United Kingdom" },
        { name: "Fordwich", country_name: "United Kingdom" },
        { name: "Seasalter", country_name: "United Kingdom" },
        { name: "Llandrillo", country_name: "United Kingdom" },
        { name: "Stratford-upon-Avon", country_name: "United Kingdom" },
        { name: "London", country_name: "United Kingdom" },
        { name: "Montgomery", country_name: "United Kingdom" },
        { name: "Murcott", country_name: "United Kingdom" },
        { name: "Biddenden", country_name: "United Kingdom" },
        { name: "Great Milton", country_name: "United Kingdom" },
        { name: "Oxford", country_name: "United Kingdom" },
        { name: "Marlow", country_name: "United Kingdom" },
        { name: "Bray", country_name: "United Kingdom" },
        { name: "Burchett's Green", country_name: "United Kingdom" },
        { name: "Egham", country_name: "United Kingdom" },
        { name: "Dublin", country_name: "Republic of Ireland" },
        { name: "Ascot", country_name: "United Kingdom" },
        { name: "Machynlleth", country_name: "United Kingdom" },
        { name: "Cheltenham", country_name: "United Kingdom" },
        { name: "Ripley", country_name: "United Kingdom" },
        { name: "Dorking", country_name: "United Kingdom" },
        { name: "Bagshot", country_name: "United Kingdom" },
        { name: "Gravetye", country_name: "United Kingdom" },
        { name: "Shinfield", country_name: "United Kingdom" },
        { name: "Horsham", country_name: "United Kingdom" },
        { name: "Newbury", country_name: "United Kingdom" },
        { name: "Malmesbury", country_name: "United Kingdom" },
        { name: "Whitebrook", country_name: "United Kingdom" },
        { name: "Llanddewi Skirrid", country_name: "United Kingdom" },
        { name: "Castle Combe", country_name: "United Kingdom" },
        { name: "Colerne", country_name: "United Kingdom" },
        { name: "East Chisenbury", country_name: "United Kingdom" },
        { name: "Winchester", country_name: "United Kingdom" },
        { name: "Bath", country_name: "United Kingdom" },
        { name: "Bristol", country_name: "United Kingdom" },
        { name: "Chew Magna", country_name: "United Kingdom" },
        { name: "Galway", country_name: "Republic of Ireland" },
        { name: "Kilkenny", country_name: "Republic of Ireland" },
        { name: "Thomastown", country_name: "Republic of Ireland" },
        { name: "Lisdoonvarna", country_name: "Republic of Ireland" },
        { name: "Ilfracombe", country_name: "United Kingdom" },
        { name: "Knowstone", country_name: "United Kingdom" },
        { name: "Lympstone", country_name: "United Kingdom" },
        { name: "Ardmore", country_name: "United Kingdom" },
        { name: "Penarth", country_name: "United Kingdom" },
        { name: "Chagford", country_name: "United Kingdom" },
        { name: "Torquay", country_name: "United Kingdom" },
        { name: "Cork", country_name: "Republic of Ireland" },
        { name: "Port Isaac", country_name: "United Kingdom" },
        { name: "Padstow", country_name: "United Kingdom" },
        { name: "Saint Helier", country_name: "United Kingdom" },
        { name: "Portscatho", country_name: "United Kingdom" },
        { name: "Ballydehob", country_name: "Republic of Ireland" },
        { name: "Baltimore", country_name: "United States" },
        { name: "Chicago", country_name: "United States" },
        { name: "New York City", country_name: "United States" },
        { name: "Washington, D.C.", country_name: "United States" }
      ]);
    });
};
